### ISSUE TITLE
 Higher GPU Memory Usage on RTX 3090 

### ISSUE THREAD

**Issue by Andy-Du20** [mr-eggplant/FOA#3]
Hi,

Thank you for your impressive work. I'm really interested in your project.

However, I've noticed that when running the code on my single RTX 3090, the GPU memory usage is about 1000 to 2000 MB higher than the values reported in your paper for various methods.

Could you please share how the GPU memory usage was calculated in the paper? Any insights you could provide would be greatly appreciated.

Thanks again for your hard work and dedication!

**Comment by Cascol-Chen** [comment]
Hi,

Thank you for your interest in our project.

Higher GPU memory usage is observed when one uses commands, such as `nvidia-smi`, to check memory usage. This is because some GPU memory, unused but cached by pytorch's allocator for acceleration, is included in the memory usage. Please refer to [here](https://pytorch.org/docs/stable/notes/cuda.html#cuda-memory-management) if you are interested in more information.

To accurately estimate the GPU memory usage, please simply add the following code from pytorch:
```python
torch.cuda.reset_peak_memory_stats()
output = model(images)
print(f'memory usage: {torch.cuda.max_memory_allocated()/(1024*1024):.3f}MB')
```

**Comment by Andy-Du20** [comment]
Thank you for your prompt response and the helpful information!
